language: node_js
sudo: true
node_js:
- '6'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.8 g++-4.8 -y
env:
- TRAVIS=travis CXX=g++-4.8
services:
- mongodb
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: qfqnOIAlSmSST2K/JvGM2uLReiJWrzpNxA78fc2gXVHfiEzjoXV5FKnP6CUHSOETX2jJvjlG2+SVQSqup+GI/RVC0esE5AWsN14YrTew9Lc49x2Q8U/tgo1OEFIueHMdyQIm4JYgYsBNDRd6C4wJtxUtLCQ8z8yVL9nlE2xgQOcDPkj0gNbf9w32RZp0vOo6DoVjHVy1OmeZI/0smZ3tL0IhSXBjAlL12a9F6Ms67Sa/BX8oI4I9Ocohi/GvK/tW7VFk3bEw1rFVfOSSlrGFrz0b66Ksr/aDXhLfk7aEMjgyOx86JPinHPkpdYdtKYGN+Nnw4GV8mo0dO76hQ9zchJUr23oNWvusA3VPm76m5Fja6+vaxos0O9fPpDPDUFiF4dY1e15cSuYHwgnmghzx7pQenV/+8MbNYSi+xQqGJg9NX+nB/I1Z9vSV+lcVLfOlHLGUaL7JQPyLO4bsUjmm2HX/3WbgUKftgeFaKNHIBefZfT7RF9tK+YvVfJze5uuyEQjwetR683xaoyL9yAuXrfszvsX5JtdUwWTkLRBzbUjVcEwBj3CzLt7DXBFPVFhZPbm+pa+20/3HNaKX9rqeTFO49KvpiKUKispNQW0wp7eamCASTQXGx+fsdMoBH8zj1c3KA+ABbMaxi6JzRP+bTXlII9EJiFqlFaPfWo8Tq6w=
  app: agile-inlet-43584
  on:
    repo: krothenbaum/map-game-restful-server
