language: node_js
sudo: true
node_js:
- '6'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.8 g++-4.8 -y
env:
- TRAVIS=travis CXX=g++-4.8
services:
- mongodb
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jLop/h39vjquCU1pUUb/Gf/P724ErlnWrEOn9TYxGs1AzoAkyqw7Jk52X4uwIL2Q9cl+7eL8mC0AR0qmIGD6gm6Is4GCel56fTGBpnK6AMF5mPtkLBZ5mfEbJRpOEP77eMb41cnG8Jo7rN33UQMS2l4c42Nk4s0bBMkGbuflrzFEjrS3knkUpNT/DX+t7I5SaKbFEYm806Q8SlVnQnKQBtWG9RuH+nOUisN0/NAojy0sHtEWj3tVjF4YLW6UTiVmD8Op96X3pmbn73HBOecB1xdzNQAg/8n82wXhcn1b9sKolKnQfB83NmBgwEux6N+yDtX9ldakYxyy6vSKsr0Eo7+U8Tdpfcn5W1w6AycEILvlc+P59WovQJpI31s5RNc2etUc/T6PPVniUkrecjgTACaFfDjQ1+xr74n7JOahiREVygnyk9UDy8KaXxW0H3mSFCpoTkPtD87AiQYa9q4PgCHtLgYaYJAfR5Qy8W56Q/qcuQRB4VCpyyPFoFphb7gEWSikZYphs/zyRhgFgqF035RM64FwasL0v/bEgTwrsAtEAZEvdfPWHbFhF2vCfjxf56VhEY/Jg/O2KRpfCG6QmgdHEBNry9D+QEeESWdWecuWpBRK7FuLDX+9vrR99Z+WDBd3n0V+SdEtQGhxJ3qOT+5ySdaMv6waj7goQiia/es=
  app: radiant-hamlet-88082
  on:
    repo: krothenbaum/map-game-restful-server
