language: node_js
sudo: true
node_js:
- '6'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.8 g++-4.8 -y
env:
- TRAVIS=travis CXX=g++-4.8
services:
- mongodb
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: "uR0O1kz4TvpDCxNkxdxXjIxNQC0zml2YrRG0IiEsBEWOk9EIoGSfSBSHCZV2W9tFkJQ7sCrWpIlXdZNH6MTcJBrxZDvEteWbay9h9bkJnVYgKwT5UQAJsYUH878VR8PS0jG+BnAveJIFK2IK66gggBdZEifDQ6fu/Q1WEyggp0l2y1L39xsTT92XvG+qIcuiunEOHymEHD9yzheuDRM4Vu2js2d0ZZpOHguxBBWdWtWE3BiNBMn3paGrIAiIXbf8AeDLxDgD9hbzl+R7L7gXJjPhh0bXb6W0TD0+OV04WxEQd+mA+HWztHTqsjAaKwa8blQZx8YYJLwLE6sB2hgiJQMnav/kDshHu+Tzny5dgGjLBUQ4JKEYa53YiMZLjiqcW2k/2rAieDt6oKrylVVRFGpJNDr1Z98L+UWpDA6zsm4jWSwvxvkVDryWdPnJDqkg2lfrI49epkV+1YBlEoNF0+JLwLS1duvoKqpJkeHkQnGlP1vhpYRamGH7wsGqa1M6+2C9PKNJZzndggoJy2qUFSdiH8rpzNBZXoBUUBL3KdJL1gT9kO7jmCYQvuZWioZjqWUy0MvnKNDqvic/YoiPI670lG8J2PjHBRUfs/H/ottDqH+xEDiuOIZ3V7yntr984eDmt85SC/qW9r7B6FtL/i6sva29n6eWOLEL7qGP7DI="
  app: agile-inlet-43584
  on:
    repo: krothenbaum/map-game-restful-server
