language: node_js
sudo: true
node_js:
- '6'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.8 g++-4.8 -y
env:
- TRAVIS=travis CXX=g++-4.8
services:
- mongodb
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: NcIq+/IW/99+aWr4uTDIUo390WGwWET2AypPinZK7bsbzHPhLJ0DCc7pNBDeuaJq0EreuaBR7KnzJhJa8aunFzOk+9rpCkaMP0Y7Q6AAI9OIR/j4YZIOkPjpCRNx1LUDhmmsHKaJ41N7b7fhzjSp2hIq0t26zZo7EyL5+AB1lsl4Uykd5K88LuDdJ8u2tN7Pft3YziViryUlp60P5Y25+FGVe0wk89iZ/S7JqOnVwvV5eVJ37pAWEqIhmmFQsqYiUVI9Hcvb6g0/NbKLmYBJUW9gZ8THfzT7AJkbwAiS0/B7UW7tp9uz1+1Pui8xH+Pn/6Un6bKsZRh6dzH6gsKAD4PTR+2CsZSsNmrbtqXUYyBkZR8ymHb2Iyy4uR6Auiwjm1YLiJDqPDhemZVgA0JJvkYb8huOFZFOaomgOQQP2y7Dvi2kPF8eQcAJSPdF9HvV3DYBdLkFLk5htbdTj/c21+f2nAulcN4mf4+IfdDnrnIyOQ5mBnJIFuW4o3KXhNDpfskagyELrnnLqFd/fU1WUHA35QI1pWbDVX77CHBK5ei7FNpvtGXLVxg3MqOFGZXBvu76RfuVrcGaDuM7fSDNJtNW6JPB1MMQmExUVm1bva073uLYBRqoRoDzj7ykyHM11udU2P0GImzK/QxAJC2GAyZsU0VhSffXJLXc26OJoT4=
  app: radiant-hamlet-88082
  on:
    repo: krothenbaum/map-game-restful-server
