language: node_js
sudo: true
node_js:
- '6'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install gcc-4.8 g++-4.8 -y
env:
- TRAVIS=travis CXX=g++-4.8
services:
- mongodb
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: eAKMbP+/j4SYjNVqKQea3KYTiMc3SOsezGzH+1uvvu/n0chgZsEAVJ/MRO5TZJxrISoBkRDQUPEikKabct2VBLUlRaczz9aDkY4ZA0co8Sc8G989ldHbysuljdl27UtHByewD5Au+/y++HSoamvGbEZagnE0tCeS4FG4rRBkm8yWetyqGBJCLBU2DiwtbTyU4VG75svKlEwwUBRSbT44n5/zMPhkIQcbE0dVAAlzcVZzxMPCr0y2MSfCrr5yvu1cXsFOivs6HAv0XzmYyBbSB2Uace11uZj5c34e8r/Gcf8QUP5sr89RJVoNEcCHya5+3buSNC1K1hyBf3FqzD96aD25QTA5/LLrUDLIKh5DYsxbiduEvxADRmWldcmqPkaLMVIVt4SIBelbKAa1pmWr62F3OM1lCOgC3X/qBFukaBC3A6ppA5O+2mBYv84nCkOwqwJ35wINCY+S8Bio2mavjSSYukGK6ZKMg8ClN9wRrDpRQX6SldoGM1RWvA9fHd2lDWRCPJ+njbxZs9bfekMFCVNxMBehoe2loeRoR9WSNtN37g4A+S9RfxjE7DlQziTVVi7TW0HnHqcMBfv2fEkOWKro9b+AH4gUtZ9lE24t7HLrOmzjrXPs520LZUu1bISAOOFNonctnzxLU5UqokTUK2oZ7GNzShIsHwJm5GbIEYE=
  app: radiant-hamlet-88082
  on:
    repo: krothenbaum/map-game-restful-server
